# 说明：配置信息 
Server:
  RunMode: debug # debug release test
  Port: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60

Database:
  DBtype: rethinkdb
  Username: root # 用户名
  Password: 123 # 密码
  Host: 119.91.204.226:32769
  DBName: chat
  Timeout: 5

Storage:
  SavePath: storage/ # 文件保存位置
  ServerUrl: http://127.0.0.1:8080/ # 静态资源服务器地址 
  ImageAllowExts: # 上传图片所允许的扩展名
    - .jpg
    - .jpeg
    - .png
    - .gif

Email: # 邮箱配置 - 用于发送邮箱验证码
  Host: "smtp-mail.outlook.com"
  Port: 587
  Username: "declinedyew@outlook.com"
  Password: "3x+4y=25"