definitions:
  model.Gender:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      Female: 女性
      Ladyboy: 中性
      Male: 男性(默认)
      Other: 其他(未知或者隐藏)
    x-enum-varnames:
    - Male
    - Female
    - Ladyboy
    - Other
  model.User:
    properties:
      address:
        type: string
      birthdate:
        type: string
      created_at:
        description: 创建时间
        type: string
      created_ip:
        description: 创建 IP 地址
        type: string
      deleted_at:
        description: 删除时间
        type: string
      email:
        type: string
      friends:
        additionalProperties:
          type: string
        description: 好友列表 备注->UserID
        type: object
      gender:
        $ref: '#/definitions/model.Gender'
      groups:
        additionalProperties:
          type: string
        description: 所属群组ID 备注->GROUPID
        type: object
      id:
        description: 模型ID
        type: string
      is_active:
        description: 是否激活
        type: boolean
      is_del:
        description: 是否删除
        type: boolean
      is_online:
        description: 是否在线
        type: boolean
      is_verified:
        description: 是否验证
        type: boolean
      last_login_at:
        type: string
      last_login_ip:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      profile_image:
        type: string
      role:
        $ref: '#/definitions/model.UserRole'
      social_accounts:
        additionalProperties:
          type: string
        type: object
      updated_at:
        description: 更新时间
        type: string
      updated_ip:
        description: 更新 IP 地址
        type: string
    type: object
  model.UserRole:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      Admin: 管理员
      Bot: 机器人
      GeneralUser: 普通人(默认)
    x-enum-varnames:
    - GeneralUser
    - Admin
    - Bot
  v1.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: Chat system developed using Gin and github.com/gobwas/ws!
  title: Chat System
  version: 1.0.0
paths:
  /v1/admin:
    post:
      consumes:
      - application/json
      description: 管理员登录
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 管理员登录
      tags:
      - user
  /v1/friend/:id:
    delete:
      consumes:
      - application/json
      description: 当前用户移除好友
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标用户 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 移除好友
      tags:
      - friend
    get:
      consumes:
      - application/json
      description: 获取当前用户指定好友信息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标用户 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 获取朋友信息
      tags:
      - friend
    post:
      consumes:
      - application/json
      description: 当前用户添加好友
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标用户 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 添加好友
      tags:
      - friend
    put:
      consumes:
      - application/json
      description: 当前用户更新好友信息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标用户 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 更新朋友信息
      tags:
      - friend
  /v1/friends/:
    get:
      consumes:
      - application/json
      description: 获取当前用户所有好友
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 获取朋友列表
      tags:
      - friend
  /v1/login:
    post:
      consumes:
      - application/json
      description: 使用电子邮件和明码进行登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 用户登录
      tags:
      - user
  /v1/logout:
    post:
      consumes:
      - application/json
      description: Log out
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 用户登出
      tags:
      - user
  /v1/me/info:
    get:
      consumes:
      - application/json
      description: 获取我的个人信息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 获取我的个人信息
      tags:
      - me
    put:
      consumes:
      - application/json
      description: 更新我的个人信息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 更新我的个人信息
      tags:
      - me
  /v1/message:
    get:
      consumes:
      - application/json
      description: 接收发送给我的消息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 接收消息
      tags:
      - message
    post:
      consumes:
      - application/json
      description: 发送我要发送的消息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 发送消息
      tags:
      - message
  /v1/message/:id:
    delete:
      consumes:
      - application/json
      description: 删除我发送的消息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标消息 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 删除消息
      tags:
      - message
    put:
      consumes:
      - application/json
      description: 更新我发送的消息
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目标消息 ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 更新消息
      tags:
      - message
  /v1/register:
    post:
      consumes:
      - application/json
      description: 使用电子邮件进行注册
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 用户注册
      tags:
      - user
  /v1/ws:
    get:
      consumes:
      - application/json
      description: 通过建立websocket协议进行用户间通信 收发消息
      parameters:
      - description: ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: 用户通信
      tags:
      - ws
swagger: "2.0"
